platform :ios, '7.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'Masonry', '~>0.6'
pod 'AFNetworking', '~> 2.6.1'
pod 'ReactiveCocoa', '~>2.5'
pod 'MJRefresh', '~> 2.4.12'
pod 'SDWebImage', '~> 3.7.3'
pod 'FMDB'
pod "SloppySwiper", '~>0.4'
pod 'MJExtension', '~> 2.5.15'
pod 'DZNEmptyDataSet', '~> 1.7.2'
pod "YYKit"
pod 'wax', :git=>'https://github.com/alibaba/wax.git', :tag=>'1.1.0'